In [9]:
# Import Library
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Dense

In [2]:
X = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0 ], dtype=float)
Y = np.array([0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5 ], dtype=float)

In [7]:
model = Sequential([
    Dense(4, input_shape=[1]), # input layer + hidden layer
    Dense(8), # hidden layer
    Dense(1), # output layer
])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 4)                 8         
                                                                 
 dense_4 (Dense)             (None, 8)                 40        
                                                                 
 dense_5 (Dense)             (None, 1)                 9         
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.compile(optimizer='sgd', loss='mse')

model.fit(X, Y, epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 1s/step - loss: 12.0554
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 2.9666
Epoch 3/500
1/1 [==============================] - 0s 5ms/step - loss: 0.8865
Epoch 4/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2617
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 0.1313
Epoch 6/500
1/1 [==============================] - 0s 6ms/step - loss: 0.1061
Epoch 7/500
1/1 [==============================] - 0s 5ms/step - loss: 0.0956
Epoch 8/500
1/1 [==============================] - 0s 5ms/step - loss: 0.0872
Epoch 9/500
1/1 [==============================] - 0s 5ms/step - loss: 0.0797
Epoch 10/500
1/1 [==============================] - 0s 7ms/step - loss: 0.0728
Epoch 11/500
1/1 [==============================] - 0s 6ms/step - loss: 0.0665
Epoch 12/500
1/1 [==============================] - 0s 5ms/step - loss: 0.0608
Epoch 13/500
1/1 [==============================] - 0s 4ms/st

In [6]:
print(X,Y) # Y = (X+2)/2

[-1.  0.  1.  2.  3.  4.  5.] [0.5 1.  1.5 2.  2.5 3.  3.5]


In [5]:
print(model.predict([-2.0, 10.0]))

[[-6.7055225e-07]
 [ 6.0000005e+00]]


In [10]:
inputs = Input(shape=[1]) # input layer
x = Dense(4)(inputs) # hidden layer
x = Dense(8)(x) # hidden layer
outputs = Dense(1)(x) # output layer
model = Model(inputs,outputs)

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense_6 (Dense)             (None, 4)                 8         
                                                                 
 dense_7 (Dense)             (None, 8)                 40        
                                                                 
 dense_8 (Dense)             (None, 1)                 9         
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(optimizer='sgd', loss='mse')

model.fit(X, Y, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 299ms/step - loss: 9.7787
Epoch 2/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6778
Epoch 3/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3252
Epoch 4/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2921
Epoch 5/500
1/1 [==============================] - 0s 7ms/step - loss: 0.2700
Epoch 6/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2496
Epoch 7/500
1/1 [==============================] - 0s 7ms/step - loss: 0.2307
Epoch 8/500
1/1 [==============================] - 0s 7ms/step - loss: 0.2132
Epoch 9/500
1/1 [==============================] - 0s 6ms/step - loss: 0.1971
Epoch 10/500
1/1 [==============================] - 0s 7ms/step - loss: 0.1821
Epoch 11/500
1/1 [==============================] - 0s 7ms/step - loss: 0.1682
Epoch 12/500
1/1 [==============================] - 0s 6ms/step - loss: 0.1554
Epoch 13/500
1/1 [==============================] - 0s 6ms/

In [12]:
print(X,Y) # Y = (X+2)/2

[-1.  0.  1.  2.  3.  4.  5.] [0.5 1.  1.5 2.  2.5 3.  3.5]


In [13]:
print(model.predict([-2.0, 10.0]))

[[-1.1026859e-06]
 [ 6.0000005e+00]]
